### ISSUE TITLE
Error with cyrillic charathers in nickname

### ISSUE THREAD

**Issue by Rubickevich** [Khaaz/Cross-Server-Bot#9] opened 2020-06-25 14:33 UTC
If nickname contains cyrillic charathers, they will not be displayed by bot.
![Снимок11](https://user-images.githubusercontent.com/54386204/85739809-cb341c00-b709-11ea-9986-4e771d99f931.PNG)
![Снимок22](https://user-images.githubusercontent.com/54386204/85739851-d2f3c080-b709-11ea-9c9f-6399f2e48fbf.PNG)

**Comment by bsian03** [comment] 2020-06-25 14:51
Issue is caused by the username filter removing any characters that aren't alphanumeric or `_!? -,.éè` characters. I'm not even sure if Discord would throw an error on names that aren't in the latin alphabet or punctuation? @Khaaz

**Comment by Khaaz** [comment] 2020-06-25 15:14
Yeah it used to be an issue in webhooks name. 
It seems that now, webhook names follow the same rules as regular username.

I'll double check for cyrillic char and other unicode. I'm working on an overall redesign and an update to the bot, this will be included in the update.

**Comment by Khaaz** [comment] 2020-07-01 15:19
fixed in latest release.
We shouldn't have any other error with nickname but I'll keep monitoring it in case there is anything wrong.

**Closed by Khaaz** 2020-07-01 15:19 UTC
Labels: bug
